AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  anon-ig-mini-demo

  Sample SAM Template for anon-ig-mini-demo
  

Resources:
  AddPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add-post/
      Handler: app.handler
      Runtime: nodejs18.x
      Events:
        AddPost:
          Type: Api
          Properties:
            Path: /posts
            Method: post
      Environment:
        Variables:
          POSTS_TABLE_NAME: !Ref PostsTable
          POSTS_BUCKET_NAME: !Ref PostImageBucket
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt PostsTable.Arn
        - S3WritePolicy:
            BucketName: !Ref PostImageBucket
  
  PostsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: post_id
          AttributeType: S
      KeySchema:
        - AttributeName: post_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  PostImageBucket:
    Type: AWS::S3::Bucket

Outputs:
  EndpointUri:
    Description: "Endpoint for API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
